---
- name: Install Homebrew on Linux
  hosts: localhost
  become: yes
  tasks:
    - name: Install dependencies for Linuxbrew
      apt:
        name:
          - build-essential
          - curl
          - file
          - git
          - sudo
        state: present
        update_cache: yes

    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew

    - name: Configure Homebrew in all user environments
      lineinfile:
        path: "{{ item }}"
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        state: present
      loop:
        - /etc/bash.bashrc   # System-wide Bash configuration
        - ~/.bashrc          # Current user Bash configuration
      become: yes  # Needed for modifying /etc/bash.bashrc

    - name: Ensure Homebrew shell environment is active in this session
      shell: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    - name: Install GCC with Homebrew
      shell: |
        brew install gcc
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/gcc

    - name: Verify Homebrew installation
      command: brew --version
      register: brew_version

    - name: Output Homebrew version
      debug:
        msg: "Homebrew installed successfully: {{ brew_version.stdout }}"



