---
- name: Setup Laptop Single Task File
  hosts: localhost
  vars:
    brewfile_path: ~/src/dotfiles/Brewfile
    dotfiles_path: ~/src/dotfiles

  tasks:
    - name: Install packages using Brewfile
      ansible.builtin.shell:
        cmd: "brew bundle --file={{ brewfile_path }}"



