---
- name: Setup Laptop Single Task File
  hosts: localhost
  vars:
    brewfile_path: ~/src/dotfiles/Brewfile

  tasks:
    - name: Ensure src exists
      ansible.builtin.file:
        path: "~/src"
        state: directory

    - name: Create .hushlogin file in home directory
      ansible.builtin.file:
        path: "~/.hushlogin"
        state: touch

    - name: Get Git repo
      ansible.builtin.git:
        repo: "git@github.com:lprior-repo/dotfiles.git"
        dest: "~/src/dotfiles"
        clone: yes
        update: yes

    - name: Install packages using Brewfile
      ansible.builtin.command:
        cmd: "brew bundle --file={{ brewfile_path }}"

    - name: Move folders to .config
      ansible.builtin.copy:
        src: "~/src/dotfiles/{{ item }}/"
        dest: "~/.config/{{ item }}/"
        remote_src: yes
        local_follow: yes
      loop:
        - zellij
        - nvim
