---
- name: Setup Laptop Single Task File
  hosts: localhost
  vars:
    brewfile_path: ~/src/dotfiles/Brewfile
    dotfiles_path: ~/src/dotfiles

  tasks:
    - name: Ensure src exists
      ansible.builtin.file:
        path: "~/src"
        state: directory

    - name: Create .hushlogin file in home directory
      ansible.builtin.file:
        path: "~/.hushlogin"
        state: touch

    - name: Get Git repo
      ansible.builtin.git:
        repo: "git@github.com:lprior-repo/dotfiles.git"
        dest: "{{ dotfiles_path }}"
        clone: yes
        update: yes

    - name: Install packages using Brewfile
      ansible.builtin.shell:
        cmd: "brew bundle --file={{ brewfile_path }}"

    - name: Install oh my zsh
      ansible.builtin.shell:
        cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

    - name: Move folders to .config
      ansible.builtin.copy:
        src: "{{ dotfiles_path }}/{{ item }}/"
        dest: "~/.config/{{ item }}/"
        remote_src: yes
        local_follow: yes
      loop:
        - zellij
        - nvim

    - name: Move .zshrc to home
      ansible.builtin.copy:
        src: "{{ dotfiles_path }}/.zshrc"
        dest: "~/.zshrc"
