- name: Setup Machine
  hosts: localhost
  become: yes
  tasks:
    - name: Install snap packages
      homebrew: 
        name: 
          - chezmoi
          - docker
          - eza
          - fd
          - fzf
          - gh
          - ghostty
          - go
          - kind
          - kubernetes-cli
          - lazygit
          - luacheck
          - neovim
          - nerdfix
          - node
          - nushell
          - ruby
          - sqlite
          - ripgrep
          - rust
          - starship
          - terraform
          - xclip
          - wezterm
          - zellij
          - zoxide
        state: latest
        update_homebrew: true
        upgrade_all: true




