- name: Setup Machine
  hosts: localhost
  become: yes
  vars:
    brew_env_line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'

  tasks:
    - name: Install snap packages
      community.general.snap: 
        name: 
          - yamllint
          - bat
          - docker
          - eza
          - fd
          - fzf
          - gh
          - go
          - kind
          - kubernetes-cli
          - lazygit
          - luacheck
          - neovim
          - nerdfix
          - node
          - nushell
          - ripgrep
          - rust
          - terraform
          - xclip
          - wezterm
          - zellij
          - zoxide
        classic: true




