theme = "papercolor-light"

[editor]
auto-save = true
auto-format = true
auto-completion = true
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
bufferline = "always"
line-number= "relative"

[editor.statusline]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "⸽"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
